weathercodes = {"3":"thunderstorms.png",
"4":"thunderstorms.png",
"5":"rain.png",
"6":"rain.png",
"7":"snow.png",
"8":"snow.png",
"9":"rain.png",
"10":"rain.png",
"11":"rain.png",
"12":"rain.png",
"13":"snow.png",
"14":"snow.png",
"15":"snow.png",
"16":"snow.png",
"17":"snow.png",
"18":"snow.png",
"19":"cloudy.png",
"20":"cloudy.png",
"21":"cloudy.png",
"22":"cloudy.png",
"23":"wind.png",
"24":"wind.png",
"25":"cloudy.png",
"26":"cloudy.png",
"27":"cloudy.png",
"28":"cloudy.png",
"29":"partly_cloudy.png",
"30":"partly_cloudy.png",
"31":"clear_night.png",
"32":"sunny.png",
"33":"sunny.png",
"34":"sunny.png",
"35":"rain.png",
"36":"sunny.png",
"37":"thunderstorms.png",
"38":"thunderstorms.png",
"39":"thunderstorms.png",
"40":"rain.png",
"41":"snow.png",
"42":"snow.png",
"43":"snow.png",
"44":"partly_cloudy.png",
"45":"thundershowers.png",
"46":"snow.png",
"47":"thunderstorms.png",
"3200":"snow.png"}

code_strings = {"3":"Thunderstorms",
"4":"Thunderstorms",
"5":"Rain",
"6":"Rain",
"7":"Snow",
"8":"Snow",
"9":"Rain",
"10":"Rain",
"11":"Rain",
"12":"Rain",
"13":"Snow",
"14":"Snow",
"15":"Snow",
"16":"Snow",
"17":"Snow",
"18":"Snow",
"19":"Cloudy",
"20":"Cloudy",
"21":"Cloudy",
"22":"Cloudy",
"23":"Windy",
"24":"Windy",
"25":"Windy",
"26":"Cloudy",
"27":"Mostly Cloudy",
"28":"Mostly Cloudy",
"29":"Partly Cloudy",
"30":"Partly Cloudy",
"31":"Clear",
"32":"Sunny",
"33":"Fair",
"34":"Fair",
"35":"Rain",
"36":"Hot",
"37":"Thunderstorms",
"38":"Thunderstorms",
"39":"Thunderstorms",
"40":"Rain",
"41":"Snow",
"42":"Snow",
"43":"Snow",
"44":"Partly Cloudy",
"45":"Thunderstorms",
"46":"Snow",
"47":"Thunderstorms",
"3200":"snow.png"}

days = {"mon":"Monday", "tue":"Tuesday", "wed":"Wednesday","thu":"Thursday","fri":"Friday","sat":"Saturday","sun":"Sunday"}